bug fix bug QUIT without register
jdomingu98/ft_irc pull request #109
Opened 2024-04-21 15:45 UTC by Atrujillo02

2024-04-21 15:48 UTC, Atrujillo02 commented
![2024-04-21_17-46](https://github.com/jdomingu98/ft_irc/assets/101263657/ac63f4e2-d11e-445d-9023-8348bd7f409c)
con mensaje y sin mensaje

2024-04-21 15:58 UTC, Atrujillo02 commented
![2024-04-21_17-56](https://github.com/jdomingu98/ft_irc/assets/101263657/780c838a-7dae-4ec7-8dcd-7bec0c413c8c)
hay este bug tambien lo añado en esta rama y lo arreglo seria bueno hacer una función que mire si no esta registrado, pero ha rellenado algun parametro lo ponga? como si pone el nick solo añadirlo en vez de una cadena vacia o asi estaria bien?

2024-04-21 17:15 UTC, jdomingu98 requested changes
Dos cosas:

1) No me gusta esa implementación, ya que eso mismo se gestiona en el for de abajo. Hay una solución más sencilla

2) La descripción de la issue estaba mal escrita, definía un comportamiento que no tiene sentido. Cuando se manda una tarea es siempre buena practica revisar por tu cuenta si lo que hay puesto tiene sentido arreglarlo o no.
En este caso no lo tenia, puesto que, al no tener datos del usuario, no se tiene forma de identificar el usuario que se está largando del server.

La descripción la tienes actualizada en la issue, pero básicamente el mensaje no se muestra cuando un usuario se registra y no se ha unido a ningún canal.

Tendrás que ver por qué el propio usuario no se incluye en la lista de usuarios a los que se les va a enviar el mensaje

2024-04-22 16:52 UTC, jdomingu98 requested changes
El primer punto del comentario de la revisión anterior lo has ignorado completamente.

Tienes un for que hace lo mismo que tu if. No sería mejor ver qué usuarios se están añadiendo a la lista, por qué no se incluye al propio usuario y arreglar eso?

Antes de mandar cualquier cosa que solucione el problema piensa si es la mejor solución. Si ves repetición en el código no es un buen indicio en la mayoría de los casos.

2024-04-23 09:52 UTC, jdomingu98 reviewed
En general ok, solo cambiar esas cosas

2024-04-23 09:52 UTC, jdomingu98 commented on src/commands/QuitCommand.cpp
> +    if (allUsers.empty() && user.isRegistered())
allUsers.empty() sobra. Investiga lo que hace un set

2024-04-23 09:52 UTC, jdomingu98 commented on src/commands/QuitCommand.cpp
> +
Esta linea sobra

2024-04-23 09:52 UTC, jdomingu98 commented on src/commands/QuitCommand.cpp
> +    if (allUsers.empty() && user.isRegistered())
Esta parte añadela antes del primer for

2024-04-23 14:45 UTC, jdomingu98 approved these changes
todo ok

2024-04-23 15:11 UTC, merged