fix: update validation
jdomingu98/ft_irc pull request #27
Opened 2024-03-18 18:43 UTC by Atrujillo02

2024-03-18 22:31 UTC, ruzafa8 commented
Me hago checkout a tu rama para compilarla @Atrujillo02 ?

2024-03-18 22:34 UTC, ruzafa8 commented
Compila ya XDD

2024-03-18 23:32 UTC, ruzafa8 reviewed
Cualquier cosa nos conectamos y lo vemos

2024-03-18 23:32 UTC, ruzafa8 reviewed
Cualquier cosa nos conectamos y lo vemos

2024-03-19 17:27 UTC, jdomingu98 commented on src/commands/NickCommand.cpp
> +
El espacio despues del if aeoa

2024-03-19 17:27 UTC, jdomingu98 requested changes
lo que dice ale

2024-03-19 18:28 UTC, jdomingu98 approved these changes
Norminette approves

2024-03-19 18:28 UTC, merged