feat; Done bug topic
jdomingu98/ft_irc pull request #85
Opened 2024-04-17 09:53 UTC by Atrujillo02

Realizado todas pruebas y arreglos con mas de un cliente y verificado con un servidor real. He probado el mode #<channel> +t ahora funciona correctamente. IMPORTANTE tendre que cambiar cuando hablemos la parte del join del libsUtils no la he cambiado porque se usa tambien en QUIT, USER, KICK lo voy a añadir a la tarea de pruebas.En contexto TOPIC falla en esto ej:
server ergo:
TOPIC #3 :                                                        hola
TOPIC se setea a :                                                        hola

ft_irc:
TOPIC #3 :                                                        hola
TOPIC se setea a :
Deberia cambiar el if() que si el primero es espacio devuelve NONE y que no se salte los espacios.

Al poder usar un servidor real me di cuenta de que si haces
TOPIC #3          hola buenas tardes
TOPIC se setea a hola
Quiere decir se queda con la primera palabra y no añade ":" ni todos los espacios, nuestro TOPIC ahora funciona igual.

2024-04-17 12:12 UTC, jdomingu98 requested changes
Los comentarios que te he puesto y la descripcion de la issue, que hay algunos test que no pasa

2024-04-17 12:12 UTC, jdomingu98 commented on includes/commands/TopicCommand.hpp
> +        bool _newTopicProvide;
Alinea

2024-04-17 12:12 UTC, jdomingu98 commented on includes/libsUtils.hpp
> +# define TOPIC_MSG(nickname, username, hostname, channelName, topic) USER_ID(nickname, username, hostname) + " TOPIC " + (channelName) + " " + (topic)
Deja los : en la macro, lo que hay que arreglar es el join auxiliar

2024-04-17 12:12 UTC, jdomingu98 commented on src/commands/TopicCommand.cpp
> -    // TODO: Check the validation order with official IRC server
Has comprobado el orden de validacion con el server oficial?

2024-04-17 12:12 UTC, jdomingu98 commented on src/commands/TopicCommand.cpp
> +        Logger::debug("Channel's topic is empty.");
Un if-else para solo poner Logger es innecesario

2024-04-17 12:12 UTC, jdomingu98 commented on src/commands/TopicCommand.cpp
> +    if (_newTopicProvide) {
Renombra la variable a _newTopicProvided

2024-04-17 12:12 UTC, jdomingu98 commented on src/parser/TopicParser.cpp
> +        return new TopicCommand(&channel, firstWord(tokens, 2));
En principio no veo necesario una funcion para buscar la primera palabra, para eso tenemos tokens[i]. Si el topic fuese algo como `TOPIC #A Este es el nuevo mensaje` El topic sería tokens[2] -> Este

2024-04-17 12:48 UTC, Atrujillo02 commented on src/commands/TopicCommand.cpp
> +        Logger::debug("Channel's topic is empty.");
pues entoces borrare los dos porque antes lo manda de forma incorrecta

2024-04-17 12:49 UTC, Atrujillo02 commented on src/parser/TopicParser.cpp
> +        return new TopicCommand(&channel, firstWord(tokens, 2));
lo he hecho pensado en el caso de antes de los espacios al principio lo probare a ver si funciona en ese caso tambien haciendo tokens[2]

2024-04-17 12:51 UTC, Atrujillo02 commented on src/commands/TopicCommand.cpp
> -    // TODO: Check the validation order with official IRC server
no lo he borrado sin querer, buscare información porque tampoco se muy bien que es exactamente

2024-04-17 15:03 UTC, ruzafa8 commented on src/commands/TopicCommand.cpp
> +    if (_newTopicProvided) {
La solución que has diseñado de una variable _newTopicProvider es correcta, incluso buena porque queda claro lo que queremos hacer. Pero, ¿podría servirnos solo con validar si _topic== NONE? Podríamos simplificar la clase y no tener que añadir un atributo más y quizás también se puede entender.

Quizas haya algún caso que se me escapa y sí es necesario hacerlo como dices. De nuevo, es solo una sugerencia, no me parece mal tu opción en realidad.

2024-04-17 15:08 UTC, ruzafa8 commented on src/parser/TopicParser.cpp
> +        return new TopicCommand(&channel, tokens[2]);
Otra sugerencia:

```
return new TopicCommand(&channel, isColonPresent(tokens) ? join(tokens, 2) : tokens[2])
```

Lo malo de esto es que no tendríamos Logger, aunque tampoco creo que sea necesario en este caso... Como prefieras, si crees que te puede ser util o whatever

2024-04-17 15:10 UTC, ruzafa8 commented on src/commands/TopicCommand.cpp
> +TopicCommand::TopicCommand(Channel *channel, const std::string& topic) : ACommand(true), _channel(channel), _topic(topic), _newTopicProvided(true){}
Tema de formateo, los `{}`los separaría, quiero decir, haces esto:
`..., _newTopicProvided(true){}`
deberíamos de hacer esto:
`..., _newTopicProvided(true) {}`

2024-04-17 15:13 UTC, jdomingu98 commented on includes/libsUtils.hpp
> +# define TOPIC_MSG(nickname, username, hostname, channelName, topic) USER_ID(nickname, username, hostname) + " TOPIC " + (channelName) + " " + (topic)
Pues es posible que se tenga que guardar los : tmb

2024-04-17 15:14 UTC, jdomingu98 commented on src/commands/TopicCommand.cpp
> -    // TODO: Check the validation order with official IRC server
Vale, lo tendré en cuenta cuando haga las pruebas. No hace falta que hagas nada

2024-04-17 15:17 UTC, jdomingu98 commented on src/parser/TopicParser.cpp
> +        return new TopicCommand(&channel, firstWord(tokens, 2));
Pero si no tiene los :, es decir,

`TOPIC #A      HOLA BUENAS TARDES`
El mensaje será un espacio

2024-04-17 15:31 UTC, Atrujillo02 commented on src/parser/TopicParser.cpp
> +        return new TopicCommand(&channel, firstWord(tokens, 2));
si esta probado y coge la primera palabra o letra, he probado tu sugerencia y sigue funcionando perfectamente asi que he borrado la funcion y lo hago como tu dices ahora

2024-04-17 15:54 UTC, Atrujillo02 commented on src/Channel.cpp
> +    for (size_t i = 0; i < allUsers.size(); i++)
ya lo he aplicado y ahora cuando termine con las demás lo subo, pero realmente tiene alguna diferencia en plan se que es poner un vector iterator en vez de size_t, pero quiero saber si es un cambio por rendimiento, estilo o seguridad?

2024-04-17 16:02 UTC, Atrujillo02 commented on src/commands/TopicCommand.cpp
> +    if (_newTopicProvided) {
Añadí el _newTopicProvided porque al hacerlo sin el, me daba fallos al gestionar si quería setear el topic a nada o quería saber el topic del canal. Porque al devolver NONE en el join del libs que es una cadena vacía y realmente se usaría para setear a la nada el topic o borrarlo, lo que hacia era devolverme el topic que ya había antes. Porque al estar topic vacío entiende que quieres ver el topic que hay, entonces pensé en dos cosas devolver un espacio en vez de NONE pero me pareció cutre y estuve bastante tiempo pensado en esa solución aunq me pareciera cutre funcionaba pero no se me quitaba de la cabeza y así con un booleano creo que esta mas claro y mejor hecho el código.

2024-04-17 22:12 UTC, jdomingu98 commented on src/Channel.cpp
> +    for (size_t i = 0; i < allUsers.size(); i++)
Los iteradores son más rapido

2024-04-18 13:49 UTC, jdomingu98 commented
He puesto el codigo, documentacion y los loggers más claros. Faltaria que arregles lo testeado en el server oficial (mira la issue de las pruebas)

2024-04-18 16:35 UTC, ruzafa8 approved these changes

2024-04-19 08:18 UTC, merged